<div class="page-header">
	<h1><?= $this->translate(strip_tags($this->headTitle()->toString())); ?></h1>
</div>
<h2><?= $this->translate("Add new expense");?></h2>
<?= $this->form; ?>
<h2><?= $this->translate("Expenses for %1\$s/%2\$s", $this->month->monthNumber, $this->month->year);?></h2>
<? if($this->month->expenses):?>
        <form method="post" action="<?= $this->url(array('action' => 'delete-expense', 'controller' => 'index')); ?>">
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>#</th>
				<th><?= $this->translate('Date');?></th>
				<th><?= $this->translate('Amount');?></th>
				<th><?= $this->translate('Category');?></th>
				<th><?= $this->translate('Annotation');?></th>
				<th> </th>
			</tr>
		</thead>
		<tbody>
			<? $i = 1; ?>
			<? foreach($this->month->expenses as $exp): ?>
				<tr>
					<td><?= $i; ?></td>
					<td><?= date("d/m/Y", $exp->date)?></td>
					<td><?= $exp->getAmountAsCurrency(); ?></td>
					<td><?= $exp->category->name ?></td>
					<td><?= $exp->description; ?></td>
					<td><input type="checkbox" name="id[]" value="<?= $exp->id; ?>"></td>
				</tr>
			<? $i++; ?>
			<? endforeach; ?>
		</tbody>
		<thead>
			<tr>
				<th> </th>
				<th><?= $this->translate('Sum');?></th>
				<th><?= $this->month->getExpensesSumAsCurrency(); ?></th>
				<th> </th>
				<th> </th>
				<th><input type="submit" class="btn btn-danger" value="<?= $this->translate('Delete'); ?>" /></th>
			</tr>
		</thead>
	</table>
        </form>
<? else: ?>
    <div class="alert alert-info">
    <a class="close" data-dismiss="alert">×</a>
    <h4 class="alert-heading">Info!</h4>
    <?= $this->translate('No expenses in database for this month, add one!');?>
    </div>
<? endif; ?>
<? 
$saveUrl = $this->url(array('action' => 'save-category', 'controller' =>'index'));
$javaScript = "$(document).ready(function() {
	$('.datepicker').datepicker({
		format: 'dd/mm/yyyy'
	})
 });"; ?>
<?= $this->inlineScript()->appendScript($javaScript); ?>