<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle(); ?>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <?php echo $this->jQuery(); ?>
    <?php echo $this->headScript(); ?>
    <?php echo $this->headLink(); ?>
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 9px 0;
      }
    </style>

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Me-Expenses</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="<?= $this->url(array('action' => 'index', 'controller' => 'index')); ?>">Home</a></li>
              <li><a href="<?= $this->url(array('action' => 'save-category', 'controller' => 'index')); ?>">Kategorie</a></li>
			  <li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><?= $this->translate('Expenses'); ?>
					<b class="caret"></b></a>
				<ul class="dropdown-menu">
              		<li><a href="<?= $this->url(array('action' => 'index', 'controller' => 'index')); ?>"><?= $this->translate('Add new'); ?></a></li>
				</ul>
			  </li>
            </ul>
            <p class="navbar-text pull-right">Logged in as <a href="#">username</a></p>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <?= $this->categorySidebar(); ?>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
        <div class="span9">
        <?php echo $this->layout()->content; ?>

        </div><!--/span-->
      </div><!--/row-->

      <hr>

      <footer>
        <p>&copy; Company 2012</p>
      </footer>

    </div><!--/.fluid-container-->
  </body>
</html>
